# Generated by Django 3.0.6 on 2020-05-24 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='type',
            new_name='protype',
        ),
    ]
