# Generated by Django 3.0.6 on 2020-05-26 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superapp', '0003_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='orders',
            field=models.ManyToManyField(blank=True, to='superapp.Product'),
        ),
    ]
