# Generated by Django 3.0.6 on 2020-05-26 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superapp', '0006_auto_20200527_0039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='orders',
            new_name='products',
        ),
    ]
